### Configurations from config server
discovery-service-user:
  server:
    hostname: localhost
    port: 8010
  credentials:
    username: user
    password: pass
#
postgres-user:
  server:
    url: 192.168.0.125
    port: 3434
    database: task_db
  credentials:
    username: postgres
    password: Fjeoqi38B3Nio83ndNehH328
#
kafka-user:
  bootstrap-servers: 192.168.0.125:29092,192.168.0.125:39092,192.168.0.125:49092
###


spring:
  application:
    name: desk-manager-ws
  profiles:
    active: discovery-service-user, postgres-user
  config:
    import: optional:configserver:http://${CONFIG_SERVER_USER}:${CONFIG_SERVER_PASSWORD}@${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8012}

  datasource:
    url: jdbc:postgresql://${postgres-user.server.url}:${postgres-user.server.port}/${postgres-user.server.database}
    username: ${postgres-user.credentials.username}
    password: ${postgres-user.credentials.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate

server.port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://${discovery-service-user.server.hostname}:${discovery-service-user.server.port}/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


